setAutoWaitTimeout(FOREVER)
#
# RED
#
switchApp("RegiStax")
sleep(1)
click("AboutCPUs.png")
click("MRUStaAlign.png")
click("1285207680462.png")
switchApp("File Browser")
type("Rtop2000\n")
wait("1285207768525.png")
sleep(3)
type("a",KEY_CTRL)
sleep(5)
dragDrop("QDDDZ2fItqDD.png", "ColourlvShow.png")
sleep(10)
click(Pattern("SelectAlignM.png").similar(0.00).targetOffset(-72,-76))

sleep(15)
click("RIIQIIStack_.png")
sleep(5)
switchApp("File Browser")
sleep(3)
type(Key.BACKSPACE)
sleep(5)
type("Gtop2000\n")
sleep(45)
type("a",KEY_CTRL)
switchApp("RegiStax")
sleep(45)
wait("100.png")
click("100.png")
click("AgEl1Armlimi.png")
sleep(5)
click("IaCkStackSta.png")
sleep(35)
wait(Pattern("1UU.png").similar(0.99))
click(Pattern("1UU.png").similar(0.99))
click(Pattern("IaCkStackSta.png").similar(0.72).targetOffset(36,-12))
sleep(1)
type("n",KEY_ALT)
sleep(2)
paste('..\\r.tif')
sleep(2)
type(Key.ENTER)
sleep(1)
#
# GREEN
#
switchApp("RegiStax")
sleep(1)
click("AboutCPUs.png")
click("MRUStaAlign.png")
click("1285207680462.png")
switchApp("File Browser")
sleep(5)
dragDrop("QDDDZ2fItqDD.png", "ColourlvShow.png")
sleep(10)
click(Pattern("SelectAlignM.png").similar(0.00).targetOffset(-72,-76))

sleep(15)
click("RIIQIIStack_.png")
sleep(5)
switchApp("File Browser")
sleep(3)
type(Key.BACKSPACE)
sleep(5)
type("Btop2000\n")
sleep(45)
type("a",KEY_CTRL)
switchApp("RegiStax")
sleep(45)
wait("100.png")
click("100.png")
click("AgEl1Armlimi.png")
sleep(5)
click("IaCkStackSta.png")
sleep(35)
wait(Pattern("1UU.png").similar(0.99))
click(Pattern("1UU.png").similar(0.99))
click(Pattern("IaCkStackSta.png").similar(0.72).targetOffset(36,-12))
sleep(1)
type("n",KEY_ALT)
sleep(2)
paste('..\\g.tif')
sleep(2)
type(Key.ENTER)
sleep(1)
#
# BLUE
#
switchApp("RegiStax")
sleep(1)
click("AboutCPUs.png")
click("MRUStaAlign.png")
click("1285207680462.png")
switchApp("File Browser")
sleep(5)
dragDrop("QDDDZ2fItqDD.png", "ColourlvShow.png")
sleep(10)
click(Pattern("SelectAlignM.png").similar(0.00).targetOffset(-72,-76))

sleep(15)
click("RIIQIIStack_.png")
sleep(5)
switchApp("File Browser")
sleep(3)
type(Key.BACKSPACE)
switchApp("RegiStax")
sleep(45)
wait("100.png")
click("100.png")
click("AgEl1Armlimi.png")
sleep(5)
click("IaCkStackSta.png")
sleep(35)
wait(Pattern("1UU.png").similar(0.99))
click(Pattern("1UU.png").similar(0.99))
click(Pattern("IaCkStackSta.png").similar(0.72).targetOffset(36,-12))
sleep(1)
type("n",KEY_ALT)
sleep(2)
paste('..\\b.tif')
sleep(2)
type(Key.ENTER)
sleep(1)