from sikuli.Sikuli import *
import os
setAutoWaitTimeout(600)
#Define Watchdog variables
CMD = "top -b -n 1 | gawk '/RegiS/ {print $9}'"
test = True
cpuMax = 10
REGISTAXWAVELETSETTING='v91.rwv'
HIDINGAPP='Chrome'
#Verify cleanup of workspace
os.popen("killall workrave")
os.popen("killall cairo-dock")
os.popen("google-chrome")
sleep(10)
#
# RED
#
os.popen("wine /home/miphilli/.wine/drive_c/Program\ Files/RegiStax\ 6/RegiStax6.exe")
os.popen("nautilus /home/miphilli/Documents/4-Temp/irisscratch\ 2000-01-01/Rtop2000")
sleep(20)
wait(Pattern("1285207768525.png").similar(0.82))
switchApp("Rtop2000")
sleep(1)
wait(Pattern("1285207768525.png").similar(0.82))
switchApp("Rtop2000")
sleep(1)
type("a",KEY_CTRL)
wait("ColourlvShow.png")
switchApp("Rtop2000")
dragDrop("QDDDZ2fItqDD.png", "ColourlvShow.png")
sleep(10)
click(Pattern("SelectAlignM.png").similar(0.00).targetOffset(-72,-76))

sleep(15)
click("RIIQIIStack_.png")
sleep(5)
switchApp("Rtop2000")
sleep(3)
type(Key.BACKSPACE)
sleep(5)
type("Gtop2000\n")
switchApp(HIDINGAPP)
while True:
	RegistaxCPU = os.popen(CMD).readlines()
	cpu = float(RegistaxCPU[0])
	if test: print cpu
	if cpu < cpuMax : break
	wait(5)
	print(RegistaxCPU)
switchApp("RegiStax")
sleep(5)
switchApp("RegiStax")
wait(Pattern("100.png").similar(0.71))
click(Pattern("100.png").similar(0.71))
click("AgEl1Armlimi.png")
wait("IaCkStackSta.png")
click("IaCkStackSta.png")
switchApp(HIDINGAPP)
while True:
	RegistaxCPU = os.popen(CMD).readlines()
	cpu = float(RegistaxCPU[0])
	if test: print cpu
	if cpu < cpuMax : break
	wait(5)
	print(RegistaxCPU)
sleep(1)
switchApp(HIDINGAPP)
sleep(1)
type(" ",KEY_ALT)
sleep(1)
type("n")
sleep(1)
switchApp("RegiStax")
sleep(5)
switchApp("RegiStax")
wait(Pattern("100.png").similar(0.68))
click(Pattern("100.png").similar(0.68))
click(Pattern("IaCkStackSta.png").similar(0.72).targetOffset(36,-12))
sleep(1)
type("n",KEY_ALT)
sleep(2)
paste('..\\r0.tif')
sleep(2)
type(Key.ENTER)
sleep(1)
click("_StackIwaygm.png")
sleep(2)
click(Pattern("Availablesch.png").similar(0.00).targetOffset(-59,-14))
sleep(2)
paste(REGISTAXWAVELETSETTING)
sleep(1)
type(Key.ENTER)
sleep(2)
click("guSlackWavel.png")
sleep(5)
click(Pattern("guSlackWavel.png").targetOffset(53,-1))
sleep(1)
type("n",KEY_ALT)
sleep(2)
paste('..\\r.tif')
sleep(2)
type(Key.ENTER)
sleep(1)
type(" ",KEY_ALT)
sleep(1)
type("c")
sleep(1)
#
# GREEN
#
os.popen("wine /home/miphilli/.wine/drive_c/Program\ Files/RegiStax\ 6/RegiStax6.exe")
wait("ColourlvShow.png")
switchApp("Gtop2000")
sleep(2)
type("a",KEY_CTRL)
sleep(2)
dragDrop("QDDDZ2fItqDD.png", "ColourlvShow.png")
sleep(10)
click(Pattern("SelectAlignM.png").similar(0.00).targetOffset(-72,-76))

sleep(15)
click("RIIQIIStack_.png")
sleep(5)
switchApp("Gtop2000")
sleep(3)
type(Key.BACKSPACE)
sleep(5)
type("Btop2000\n")
switchApp(HIDINGAPP)
while True:
	RegistaxCPU = os.popen(CMD).readlines()
	cpu = float(RegistaxCPU[0])
	if test: print cpu
	if cpu < cpuMax : break
	wait(5)
	print(RegistaxCPU)
switchApp(HIDINGAPP)
sleep(1)
switchApp("RegiStax")
sleep(5)
switchApp("RegiStax")
wait(Pattern("100.png").similar(0.71))
click(Pattern("100.png").similar(0.71))
click("AgEl1Armlimi.png")
wait("IaCkStackSta.png")
click("IaCkStackSta.png")
switchApp(HIDINGAPP)
while True:
	RegistaxCPU = os.popen(CMD).readlines()
	cpu = float(RegistaxCPU[0])
	if test: print cpu
	if cpu < cpuMax : break
	wait(5)
	print(RegistaxCPU)
sleep(1)
type(" ",KEY_ALT)
sleep(1)
type("n")
sleep(1)
switchApp("RegiStax")
sleep(5)
switchApp("RegiStax")
wait(Pattern("100.png").similar(0.68))
click(Pattern("100.png").similar(0.68))
click(Pattern("IaCkStackSta.png").similar(0.72).targetOffset(36,-12))
sleep(1)
type("n",KEY_ALT)
sleep(2)
paste('..\\g0.tif')
sleep(2)
type(Key.ENTER)
sleep(1)
#popup("Clicking Wavelets next")
click("_StackIwaygm.png")
sleep(2)
click(Pattern("Availablesch.png").similar(0.00).targetOffset(-59,-14))
#popup("Did I just hit the load wavelets settings?")
sleep(2)
paste(REGISTAXWAVELETSETTING)
sleep(1)
type(Key.ENTER)
sleep(2)
click("guSlackWavel.png")
sleep(5)
#popup("Just hit doall next save image")
click(Pattern("guSlackWavel.png").targetOffset(53,-1))
sleep(1)
type("n",KEY_ALT)
sleep(2)
paste('..\\g.tif')
sleep(2)
type(Key.ENTER)
sleep(1)
type(" ",KEY_ALT)
sleep(1)
type("c")
sleep(1)
#
# BLUE
#
os.popen("wine /home/miphilli/.wine/drive_c/Program\ Files/RegiStax\ 6/RegiStax6.exe")
wait("ColourlvShow.png")
switchApp("Btop2000")
sleep(2)
type("a",KEY_CTRL)
sleep(2)
dragDrop("QDDDZ2fItqDD.png", "ColourlvShow.png")
sleep(10)
click(Pattern("SelectAlignM.png").similar(0.00).targetOffset(-72,-76))
sleep(15)
click("RIIQIIStack_.png")
sleep(5)
switchApp("Btop2000")
sleep(3)
type(Key.BACKSPACE)
switchApp(HIDINGAPP)
while True:
	RegistaxCPU = os.popen(CMD).readlines()
	cpu = float(RegistaxCPU[0])
	if test: print cpu
	if cpu < cpuMax : break
	wait(5)
	print(RegistaxCPU)
switchApp("RegiStax")
sleep(5)
switchApp("RegiStax")
wait(Pattern("100.png").similar(0.71))
click(Pattern("100.png").similar(0.71))
click("AgEl1Armlimi.png")
wait("IaCkStackSta.png")
click("IaCkStackSta.png")
switchApp(HIDINGAPP)
while True:
	RegistaxCPU = os.popen(CMD).readlines()
	cpu = float(RegistaxCPU[0])
	if test: print cpu
	if cpu < cpuMax : break
	wait(5)
	print(RegistaxCPU)
sleep(1)
switchApp(HIDINGAPP)
sleep(1)
type(" ",KEY_ALT)
sleep(1)
type("n")
sleep(1)
switchApp("RegiStax")
sleep(5)
switchApp("RegiStax")
wait(Pattern("100.png").similar(0.68))
click(Pattern("100.png").similar(0.68))
click(Pattern("IaCkStackSta.png").similar(0.72).targetOffset(36,-12))
sleep(1)
type("n",KEY_ALT)
sleep(2)
paste('..\\b0.tif')
sleep(2)
type(Key.ENTER)
sleep(1)
click("_StackIwaygm.png")
sleep(2)
click(Pattern("Availablesch.png").similar(0.00).targetOffset(-59,-14))
sleep(2)
paste(REGISTAXWAVELETSETTING)
sleep(1)
type(Key.ENTER)
sleep(2)
click("guSlackWavel.png")
sleep(5)
click(Pattern("guSlackWavel.png").targetOffset(53,-1))
sleep(1)
type("n",KEY_ALT)
sleep(2)
paste('..\\b.tif')
sleep(2)
type(Key.ENTER)
sleep(1)
type(" ",KEY_ALT)
sleep(1)
type("c")
sleep(1)
switchApp("irisscratch")
sleep(2)
type(" ",KEY_ALT)
sleep(1)
type("c")
#Reset workspace
#sleep(2)
#switchApp('FOLDERSWAPPER')
#sleep(2)
#type(" ")
